### ISSUE TITLE
comments from david 2

### ISSUE THREAD

**Issue by gangtao** [timeplus-io/kafka-connect-timeplus#4]
TimeplusSinkConnectorConfig
- Should consider setting the APIKEY_CONFIG as Type.Password as this may contain sensitive information that may get logged.

TimeplusSinkTask
- Ability to set some of the variables to private and/or private final scope.
- Line 69 - v1beta1 could be moved out to a property value, similar to version
- Line 96 - Could be better used as a Stringbuilder.
- Lines 117, 174, 200 - Recommend to use try-with-resources here; or else have a finally block to close out the response object in case of a catch exception not reaching that far
- Line 122 - Catch prints the warning but doesn't handle the underlying exception.
- Line 136-138 - Can make one of those finally and avoid repeated object creation for a similar object
- Line 149 - typo in columns
- Lines 173, 202 - can produce a NullPointerException when getting response body string.

IntegrationTest
- This test would not run for me locally either from IntelliJ or Terminal; gives me a connection refused - I am running on Mac (find logs at the end of the email)
- Missing @Testcontainers annotation at the top of the class to activate the @Container annotations
- kafkaConect should depend on kafka container having started successfully
- timeplus/timeplus-kafkaconnect-sink:latest will test against the latest version rather than a fixed release; also always pull containers may be expensive for repeated runs on DockerHub - is that OK?

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
